### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by ninetalescommander** [KozGit/Blender-2.8-MD5-import-export-addon#21]
Python: Traceback (most recent call last):
  File "C:\Users\maste\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_md5_28.py", line 1066, in execute
    read_md5mesh(self.filepath, correctionMatrix, self.mergeVerticesCM * 0.01, self.boneLayer-1)
  File "C:\Users\maste\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_md5_28.py", line 94, in read_md5mesh
    arm_o, ms = do_joints(md5mesh, j_re, e_re, matrix,meshName,collection,boneLayer)
  File "C:\Users\maste\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_md5_28.py", line 200, in do_joints
    b.layers[bl] = True
AttributeError: 'Bone' object has no attribute 'layers'

I keep getting this error on importing, how do I fix it?

**Comment by kjhyhy6765** [comment]
heres the fix:
so go to your **C:\Users\ _pick the name_ \AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons** and find io_scene_md5_28.py right click it and edit with notepad or whatever other software. Now CTRL+F and find the line **b.layers[bl] = True** and replace it with **b.select = True**
Now the object should import but the animations will still not work
CTRL+F again and find **return btb(None, [b for b in arm.bones if b.layers[bl]])** you may need to delete some letters for it to find it and replace it with **return btb(None, arm.bones)  # Pass all bones**
Again, CTRL+F and find the last line **if armature.animation_data.action.name == actionName:** and replace it with **if armature.animation_data and armature.animation_data.action and armature.animation_data.action.name == actionName:** save the .py and it should work for both importing a object + animation.

Note that I'm using the newest version of blender 4.2.3

**Comment by LWSS** [comment]
the meshes are still fubar. I just downgraded to blender 2.8 for now. Some sort of API problem going on here.

**Comment by KozGit** [comment]
These issues are due to API changes in blender 4.0+.  Starting in 4.0, Blender removed bone layers and changed to bone collections, along with a few other minor changes.  Any blender prior to 4.0 (2.8x - 3.xx) should work.  Unfortunately the script will need to be updated to support 4.0+
