### ISSUE TITLE
failed import on 4.2.3

### ISSUE THREAD

**Issue by kjhyhy6765** [KozGit/Blender-2.8-MD5-import-export-addon#22]
Line: (b.layers[bl] = True) In recent versions of Blender (such as Blender 4.x), the Bone object no longer has a layers attribute. Instead of using b.layers, you will need to work with Bone Collections or Bone Groups (if appropriate) as Blender has moved away from the layer system for bones. 
-Gpt  diagnosis. 
my error code
Python: Traceback (most recent call last):
  File "C:\Users\jackr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_md5_28.py", line 1066, in execute
    read_md5mesh(self.filepath, correctionMatrix, self.mergeVerticesCM * 0.01, self.boneLayer-1)
  File "C:\Users\jackr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_md5_28.py", line 94, in read_md5mesh
    arm_o, ms = do_joints(md5mesh, j_re, e_re, matrix,meshName,collection,boneLayer)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jackr\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_md5_28.py", line 200, in do_joints
    b.layers[bl] = True
    ^^^^^^^^
AttributeError: 'Bone' object has no attribute 'layers'

**Comment by kjhyhy6765** [comment]
fixed it, 
so go to your **C:\Users\ _pick the name_ \AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons** and find io_scene_md5_28.py right click it and edit with notepad or whatever other software. Now CTRL+F and find the line **b.layers[bl] = True** and replace it with **b.select = True**
Now the object should import but the animations will still not work
CTRL+F again and find **return btb(None, [b for b in arm.bones if b.layers[bl]])** you may need to delete some letters for it to find it and replace it with **return btb(None, arm.bones)  # Pass all bones**
Again, CTRL+F and find the last line **if armature.animation_data.action.name == actionName:** and replace it with **if armature.animation_data and armature.animation_data.action and armature.animation_data.action.name == actionName:** save the .py and it should work for both importing a object + animation.
